///login

export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_ERROR = "FETCH_LOGIN_ERROR";

/// blog

export const FETCH_BLOG_REQUEST = "FETCH_BLOG_REQUEST";
export const FETCH_BLOG_SUCCESS = "FETCH_BLOG_SUCCESS";
export const FETCH_BLOG_ERROR = "FETCH_BLOG_ERROR";

// productdetail

export const FETCH_PRODUCT_DETAIL_REQUEST = "FETCH_PRODUCT_DETAIL_REQUEST";
export const FETCH_PRODUCT_DETAIL_SUCCESS = "FETCH_PRODUCT_DETAIL_SUCCESS";
export const FETCH_PRODUCT_DETAIL_ERROR = "FETCH_PRODUCT_DETAIL_ERROR";

///product

export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";

/// addproduct

export const FETCH_ADD_PRODUCT_REQUEST = "FETCH_ADD_PRODUCT_REQUEST";
export const FETCH_ADD_PRODUCT_SUCCESS = "FETCH_ADD_PRODUCT_SUCCESS";
export const FETCH_ADD_PRODUCT_ERROR = "FETCH_ADD_PRODUCT_ERROR";

/// brand

export const FETCH_BRAND_REQUEST = "FETCH_BRAND_REQUEST";
export const FETCH_BRAND_SUCCESS = "FETCH_BRAND_SUCCESS";
export const FETCH_BRAND_ERROR = "FETCH_BRAND_ERROR";

//
/// home

export const FETCH_HOME_REQUEST = "FETCH_HOME_REQUEST";
export const FETCH_HOME_SUCCESS = "FETCH_HOME_SUCCESS";
export const FETCH_HOME_ERROR = "FETCH_HOME_ERROR";

/// add to  cart

export const FETCH_CART_REQUEST = "FETCH_CART_REQUEST";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_ERROR = "FETCH_CART_ERROR";
export const ADD_TO_CART = "ADD_TO_CART";

/// cart

export const FETCH_All_CART_REQUEST = "FETCH_All_CART_REQUEST";
export const FETCH_ALL_CART_SUCCESS = "FETCH_ALL_CART_SUCCESS";
export const FETCH_ALL_CART_ERROR = "FETCH_ALL_CART_ERROR";
